# Generated by Django 4.2.30 on 2026-09-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='timeline_events',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
